spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giggy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Qeeq.0389

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

#spring:
#  application:
#    name: giggy
#
## MYSQL ??
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/giggy?useSSL=false&serverTimezone=Asia/Seoul
#spring.datsource.username=root
#spring.datasource.password=Qeeq.0389
#
## ?? SQL ??
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect